name: FAIR Data Pipeline Chocolatey Packages
on: [push]
jobs:
  fair-cli:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Choco pack
        run: choco pack
        working-directory: ./fair-cli

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Choco install test
        run: choco install -y fair-cli -dv -s .
        working-directory: ./fair-cli
